Assignment 6 OOPs Implementation added
Dharanash15/SolitonTemplate pull request #10
Opened 2023-09-05 08:40 UTC by Dharanash15

2023-09-07 03:28 UTC, arun-soliton requested changes
Make changes based on comments

2023-09-07 03:28 UTC, arun-soliton commented on src/Assignment6/ShapeHierarchy/Circle.cs
> +        private int radius;
The order in which you would arrange the fields, methods, constructor, and properties is below. Change the order accordingly.

1. Fileds 
2. Properties
3. Class Constructor
4. Methods

2023-09-07 03:28 UTC, arun-soliton commented on src/Assignment6/ShapeHierarchy/Circle.cs
> +        private int radius;
Why is the documentation not added for the field `radius`

2023-09-07 03:28 UTC, arun-soliton commented on src/Assignment6/ShapeHierarchy/Rectangle.cs
> +        private int breath;
Why is no documentation for the fields?

2023-09-07 03:28 UTC, arun-soliton commented on src/Assignment6/ShapeHierarchy/Rectangle.cs
> +        private string Shape { get; set; }
No documentation was added. Kindly add it.

2023-09-07 03:28 UTC, arun-soliton commented on src/Assignment6/ShapeHierarchy/Rectangle.cs
> +            return IsValidInput(length, breath);
The same comment was given for the circle as well. Make changes accordingly.

2023-09-07 03:28 UTC, arun-soliton commented on src/Assignment6/ShapeHierarchy/Rectangle.cs
> +        }
check the alignment of braces.

2023-09-07 03:28 UTC, arun-soliton commented on src/Assignment6/ShapeHierarchy/Rectangle.cs
> +            }
`else` statement not required

2023-09-07 03:28 UTC, arun-soliton commented on src/Assignment6/EmployeeHierarchy/Employee.cs
> +            }
When you have a method like `IsValidInput`, it should only return a `Boolean`, the name of the method should be changed accordingly. Or the implementation must be changed

2023-09-07 03:28 UTC, arun-soliton commented on src/Assignment6/BankingSystem/Program.cs
> +            }
Check the alignment and change it accordingly.

2023-09-07 03:28 UTC, arun-soliton commented on src/Assignment6/BankingSystem/Program.cs
> +                    }
Change the alignment properly.

2023-09-07 05:59 UTC, Dharanash15 commented on src/Assignment6/ShapeHierarchy/Circle.cs
> +        private int radius;
Usually, properties alone require documentation as per starter template. I didn't know about the documentation of filed . Sure I will add it.

2023-09-07 06:00 UTC, Dharanash15 commented on src/Assignment6/ShapeHierarchy/Rectangle.cs
> +        private int breath;
Same as mention.

2023-09-07 06:02 UTC, Dharanash15 commented on src/Assignment6/ShapeHierarchy/Rectangle.cs
> +        private string Shape { get; set; }
we usually don't do documentation for private properties. If it was a standard it will add it.

2023-09-07 06:03 UTC, Dharanash15 commented on src/Assignment6/EmployeeHierarchy/Employee.cs
> +            }
Sure

2023-09-07 08:58 UTC, Dharanash15 commented on src/Assignment6/BankingSystem/Program.cs
> +            }
resolved

2023-09-07 08:59 UTC, Dharanash15 commented on src/Assignment6/BankingSystem/Program.cs
> +                    }
resolved

2023-09-07 09:21 UTC, Dharanash15 commented on src/Assignment6/ShapeHierarchy/Rectangle.cs
> +            return IsValidInput(length, breath);
resolved

2023-09-07 09:21 UTC, Dharanash15 commented on src/Assignment6/ShapeHierarchy/Rectangle.cs
> +            }
removed.

2023-09-07 09:21 UTC, Dharanash15 commented on src/Assignment6/ShapeHierarchy/Rectangle.cs
> +        }
resolved

2023-09-07 17:04 UTC, arun-soliton requested changes
I have added comments for the things, pushed before we had a call. Make changes that we discussed over a call.

2023-09-07 17:04 UTC, arun-soliton commented on src/Assignment6/ShapeHierarchy/Circle.cs
> +        }
We can make changes to the current implementation.
Inside Calculate Area, do the following things in order,
1. call `GetCircleDetails()`
2. call `IsValidRadius()` - check valid or not (Change the name of the method as mentioned)
3. If valid - calculate and return the area
4. If Invalid, show error message and return 0

2023-09-07 17:04 UTC, arun-soliton commented on src/Assignment6/ShapeHierarchy/Circle.cs
> +                return false;
Make a common implementation for showing the error and modify accordingly

2023-09-09 01:44 UTC, arun-soliton requested changes
Make changes based on comments.

2023-09-09 01:44 UTC, arun-soliton commented on src/Assignment6/Utility/Utility.cs
> +        }
![image](https://github.com/Dharanash15/SolitonTemplate/assets/136311111/4ebc97d3-5666-469c-b110-7f085ba9d6a3)
We could have one line of spacing before printing the error message and make the two line spacing as one in the console.

2023-09-09 01:44 UTC, arun-soliton commented on src/Assignment6/EmployeeHierarchy/Employee.cs
> +        public decimal SetValidSalary(string input)
Name of the method could be `CheckAndUpdateSalary`

2023-09-09 01:44 UTC, arun-soliton commented on src/Assignment6/EmployeeHierarchy/Employee.cs
> +    /// Act as a parent class and also abstract methods for other classes.
```suggestion
    /// Parent class for Employee Hierarchy
```

2023-09-09 01:44 UTC, arun-soliton commented on src/Assignment6/EmployeeHierarchy/Manager.cs
> +            Salary = SetValidSalary(salary);
Change the name accordingly.

2023-09-09 01:44 UTC, arun-soliton commented on src/Assignment6/Utility/Utility.cs
> +        }
![image](https://github.com/Dharanash15/SolitonTemplate/assets/136311111/9db060b3-6c58-4284-aa9f-aa411d4aa912)

Same as above.

2023-09-09 01:44 UTC, arun-soliton commented on src/Assignment6/BankingSystem/CheckingAccount.cs
> +            Console.ForegroundColor = ConsoleColor.Red;
Changing of the console line color is not needed here.

2023-09-09 01:44 UTC, arun-soliton commented on src/Assignment6/BankingSystem/Program.cs
> +        public static void TransactionOnBankAccounts(BankAccount accountType)
The name of the method could be `MakeTransactionOnBankAccounts`

2023-09-09 01:44 UTC, arun-soliton commented on src/Assignment6/Readme.md
> +This is the C# console application. This is used to perform the object oriented programming. This program creates the different class for each of the task. Each class has the different methods and pr
Instead of using `This`, you could use - The project/Assignment 6 is a console application.

2023-09-09 15:50 UTC, Dharanash15 commented on src/Assignment6/ShapeHierarchy/Circle.cs
> +                return false;
resolved

2023-09-09 15:50 UTC, Dharanash15 commented on src/Assignment6/ShapeHierarchy/Circle.cs
> +        }
resolved

2023-09-09 15:51 UTC, Dharanash15 commented on src/Assignment6/Utility/Utility.cs
> +        }
Sure!

2023-09-09 15:51 UTC, Dharanash15 commented on src/Assignment6/EmployeeHierarchy/Employee.cs
> +    /// Act as a parent class and also abstract methods for other classes.
resolved

2023-09-09 15:51 UTC, Dharanash15 commented on src/Assignment6/Utility/Utility.cs
> +        }
resolved

2023-09-09 15:51 UTC, Dharanash15 commented on src/Assignment6/BankingSystem/CheckingAccount.cs
> +            Console.ForegroundColor = ConsoleColor.Red;
Yes, Resolved.

2023-09-09 15:52 UTC, Dharanash15 commented on src/Assignment6/Readme.md
> +This is the C# console application. This is used to perform the object oriented programming. This program creates the different class for each of the task. Each class has the different methods and pr
resolved

2023-09-09 15:52 UTC, Dharanash15 commented on src/Assignment6/BankingSystem/Program.cs
> +        public static void TransactionOnBankAccounts(BankAccount accountType)
Resolved

2023-09-09 15:56 UTC, Dharanash15 commented on src/Assignment6/EmployeeHierarchy/Employee.cs
> +        public decimal SetValidSalary(string input)
resolved

2023-09-09 15:57 UTC, Dharanash15 commented on src/Assignment6/EmployeeHierarchy/Manager.cs
> +            Salary = SetValidSalary(salary);
resolved

2023-09-11 02:45 UTC, merged