Feat assignment3 dependencyfileadded
Dharanash15/SolitonTemplate pull request #3
Opened 2023-08-22 11:15 UTC by Dharanash15

2023-09-03 16:39 UTC, arun-soliton requested changes
Kindly make changes based on the comments.

2023-09-03 16:39 UTC, arun-soliton commented on src/Assisgnment3/MathApp/MathApp.cs
> +    public class MathApp : InterfaceCB
Can we rename the class name as `MathFunctions`, when I went through the documentation I felt that the namings used were more good, but when I went through the implementation it was different.

2023-09-03 16:39 UTC, arun-soliton commented on src/Assisgnment3/MathApp/MathApp.cs
> +        }
When this method has no use, it is redundant right why can't we remove that?

2023-09-03 16:39 UTC, arun-soliton commented on src/Assisgnment3/Interface/InterfaceCB.cs
> +    public interface InterfaceCB
The name of the interface can be changed, it could be like the one which you have mentioned in the `Readme.md` file.

2023-09-03 16:39 UTC, arun-soliton commented on src/Assisgnment3/Interface/InterfaceCB.cs
> +        }
I think this method is redundant and can be removed.

2023-09-03 16:39 UTC, arun-soliton commented on src/Assisgnment3/Interface/InterfaceCB.cs
> +    /// Interface for DisplayApp and MathApp
```suggestion
    /// Interface for Math operations
```

2023-09-03 16:39 UTC, arun-soliton commented on src/Assisgnment3/DisplayApp/DisplayApp.cs
> +        private static InterfaceCB? _interfaceMathApp;
Name of the defined interface can be changed as per the name given in `Readme.md` file

2023-09-03 16:39 UTC, arun-soliton commented on src/Assisgnment3/DisplayApp/DisplayApp.cs
> +        ///     Displays the operation of functionalities
```suggestion
        /// Displays the operation of functionalities
```

2023-09-03 16:39 UTC, arun-soliton commented on src/Assisgnment3/UtilityApp/UtilityApp.cs
> +        }
Redundant method can be removed

2023-09-03 16:39 UTC, arun-soliton commented on src/Assisgnment3/GreetingApp/GreetingApp.cs
> +            MathApp mathObj = new MathApp();
The name of the created object can be more meaningful. `mathApp` itself is a much more meaningful name

2023-09-03 16:39 UTC, arun-soliton commented on src/Assisgnment3/GreetingApp/GreetingApp.cs
> +            DisplayApp displayObj = new DisplayApp(mathObj);
Change the name of the object created by `DisplayApp`

2023-09-03 16:39 UTC, arun-soliton commented on src/Assisgnment3/DisplayApp/DisplayApp.cs
> +            UtilityApp check = new UtilityApp();
Name of the object created from `UtilityApp` can be much more meaningful

2023-09-03 16:39 UTC, arun-soliton commented on src/Assisgnment3/DisplayApp/DisplayApp.cs
> +            while (true)
We can remove `while(true)` here, let user can do only one operation

2023-09-03 16:39 UTC, arun-soliton commented on src/Assisgnment3/DisplayApp/DisplayApp.cs
> +        }
The redundant method can be removed

2023-09-03 16:39 UTC, arun-soliton commented on src/Assisgnment3/DisplayApp/DisplayApp.cs
> +                        goto loop;
`goto` statement can be removed

2023-09-03 16:39 UTC, arun-soliton commented on src/Assisgnment3/DisplayApp/DisplayApp.cs
> +                    goto loop;
Remove the `goto` statement

2023-09-04 05:08 UTC, Dharanash15 commented on src/Assisgnment3/MathApp/MathApp.cs
> +        }
A project cannot be without main function in our stater template. I understand that we can create a project without main function if it was a class but as per the documentation it was not possible in this scenario.

2023-09-04 05:10 UTC, Dharanash15 commented on src/Assisgnment3/Interface/InterfaceCB.cs
> +        }
same as I mentioned above

2023-09-04 06:00 UTC, Dharanash15 commented on src/Assisgnment3/MathApp/MathApp.cs
> +    public class MathApp : InterfaceCB
Resolved

2023-09-04 06:24 UTC, Dharanash15 commented on src/Assisgnment3/MathApp/MathApp.cs
> +        }
ok, I found a way to remove it. Thanks for your comment.

2023-09-04 07:00 UTC, Dharanash15 commented on src/Assisgnment3/Interface/InterfaceCB.cs
> +    public interface InterfaceCB
Resolved

2023-09-04 07:04 UTC, Dharanash15 commented on src/Assisgnment3/Interface/InterfaceCB.cs
> +    /// Interface for DisplayApp and MathApp
resolved

2023-09-04 08:45 UTC, Dharanash15 commented on src/Assisgnment3/DisplayApp/DisplayApp.cs
> +                        goto loop;
resolved

2023-09-04 08:45 UTC, Dharanash15 commented on src/Assisgnment3/DisplayApp/DisplayApp.cs
> +        }
resolved

2023-09-04 08:46 UTC, Dharanash15 commented on src/Assisgnment3/Interface/InterfaceCB.cs
> +    /// Interface for DisplayApp and MathApp
resolved

2023-09-05 03:02 UTC, arun-soliton commented on src/Assignment3/DisplayApp/DisplayApplication.cs
> +        public DisplayApplication(IMathOperation mathFunctionObject)
```suggestion
        public DisplayApplication(IMathOperation mathFunction)
```

2023-09-05 03:02 UTC, arun-soliton commented on src/Assignment3/DisplayApp/DisplayApplication.cs
> +            _interfaceMathFunctions = mathFunctionObject;
Change the name for both as given in the comment previously

2023-09-05 03:03 UTC, arun-soliton commented on src/Assignment3/DisplayApp/DisplayApplication.cs
> +            Utilize IsUserInputValid = new Utilize();
Change the name to `Utils` and created object can have the name `utils'

2023-09-05 03:04 UTC, arun-soliton commented on src/Assignment3/DisplayApp/DisplayApplication.cs
> +                    Console.WriteLine($"Division of given inputs is : {_interfaceMathFunctions.Divide(input1, input2)}");
Change the name of the created objects accordingly, w.r.t the comment given above

2023-09-05 03:05 UTC, arun-soliton commented on src/Assignment3/GreetingApp/GreetingApplication.cs
> +            MathFunctions passMathFunctionObject = new MathFunctions();
name of the created object for `MathFunctions` can be `mathFunctions` itself

2023-09-05 03:06 UTC, arun-soliton commented on src/Assignment3/UtilityApp/Utilize.cs
> +    public class Utilize
Name of the class can be `Utils` and it can be `Utility` also

2023-09-05 03:56 UTC, Dharanash15 commented on src/Assignment3/DisplayApp/DisplayApplication.cs
> +    using Utilize;
Resolved

2023-09-05 03:56 UTC, Dharanash15 commented on src/Assignment3/DisplayApp/DisplayApplication.cs
> +        private static IMathOperation? _interfaceMathFunctions;
Resolved

2023-09-05 03:56 UTC, Dharanash15 commented on src/Assignment3/DisplayApp/DisplayApplication.cs
> +        public DisplayApplication(IMathOperation mathFunctionObject)
Resolved

2023-09-05 03:57 UTC, Dharanash15 commented on src/Assignment3/DisplayApp/DisplayApplication.cs
> +            _interfaceMathFunctions = mathFunctionObject;
Resolved

2023-09-05 04:00 UTC, Dharanash15 commented on src/Assignment3/DisplayApp/DisplayApplication.cs
> +            Utilize IsUserInputValid = new Utilize();
resolved

2023-09-05 04:00 UTC, Dharanash15 commented on src/Assignment3/DisplayApp/DisplayApplication.cs
> +                    Console.WriteLine($"Division of given inputs is : {_interfaceMathFunctions.Divide(input1, input2)}");
resolved

2023-09-05 04:01 UTC, Dharanash15 commented on src/Assignment3/UtilityApp/Utilize.cs
> +    public class Utilize
resolved

2023-09-05 04:13 UTC, arun-soliton approved these changes
Reviewed and approved

2023-09-05 05:16 UTC, merged