Feat: assignment6 oops implementation added
Dharanash15/SolitonTemplate pull request #4
Opened 2023-08-24 08:29 UTC by Dharanash15

2023-09-03 13:15 UTC, arun-soliton requested changes
Kindly make changes based on the comments.

2023-09-03 13:15 UTC, arun-soliton commented on src/Assignment6/BankingSystem/Program.cs
> +                    SavingsAccount savingsAccount = new SavingsAccount(accountNumber);
`Program.cs` can have only logics like creating respective classes based on user options and calling the respective methods. Try making the change.

2023-09-05 04:39 UTC, merged

2023-09-05 10:47 UTC, Dharanash15 commented on src/Assignment6/ShapeHierarchy/Circle.cs
> +            return Math.PI * radius * radius;
I create a new method to resolve it.

2023-09-05 10:49 UTC, Dharanash15 commented on src/Assignment6/ShapeHierarchy/Circle.cs
> +        /// Method to calculate area from the given input
resolved

2023-09-05 10:54 UTC, Dharanash15 commented on src/Assignment6/ShapeHierarchy/Rectangle.cs
> +        /// Method declared to print details of shape in child class
resolved

2023-09-05 10:55 UTC, Dharanash15 commented on src/Assignment6/ShapeHierarchy/Rectangle.cs
> +        /// <param name="area">area of a given shape</param>
resolved